@UserRegApi_HostAddress = https://localhost:7102

POST {{UserRegApi_HostAddress}}/api/Auth/Login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password"
}

###

GET {{UserRegApi_HostAddress}}/api/User/GetList
Authorization: Bearer {{token}}

###
